version: '3.8'
services:
  management-app:
    build: .
    ports: 
      - 3000:80
    image: registry.punk.link/management-app:latest
    healthcheck:
      test: curl --fail http://127.0.0.1/health || exit 1
      interval: 1m
      timeout: 3s
      retries: 5
      start_period: 30s